# my_workspace/Cargo.toml
[workspace]
resolver = "2"
members = ["examples/example", "hocuspocus-rs-ws"]
default-members = ["examples/example"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
